### ISSUE TITLE
Menšie úpravy

### ISSUE THREAD

**Issue by Mcibula** [TIS2023-FMFI/pracovne-cesty#116]
- [x] Premenovať pani tajomníčku v seederi a v DB #118 
- [x] Adminovi sprístupniť všetky dopravné prostriedky #119 
- [x] Ošetrit prístup iba k vlastným cestám #122 
- [x] Reset hesla iba pre vybraných ľudí (neregistrovaných v Prítomnosti) #123 
- [x] Upraviť názov sekcie bez mena #119 
- [x] Pridať transakcie pri create #122 
- [x] Nechať formulár pre admina editovateľný, aj ak je cesta CLOSED #119 
- [x] Pridať niektoré form fields do FixedFormFields, takže sa nedajú upraviť v stave CONFIRMED #119 
- [ ] Zmeniť link field na `<a>`, aby sa naň dalo klikať
- [x] Upraviť veľkosť textov v generovaných dokumentoch #120 
- [x] Pridať trip purposes do seederov #121 
- [x] Opraviť nesprávne párovanie prínosu cesty s jej detailom v Dohode #125 
- [x] Zmeniť detail cesty v Prítomnosti #122 
- [x] Upraviť mailové templates #126 
- [x] Ošetriť na backende, ktoré dokumenty si user môže vygenerovať #126 
- [x] Pridať transakcie k Prítomnosti a dočasne deaktivovať synchronizáciu ciest #129 
- [ ] Opraviť počítanie dní (trvanie cesty)
---
- [x] Pridať prázdny ŠPP prvok #121 
- [x] Pridať ŠPP prvky #121 
- [x] Upraviť stĺpce v ŠPP prvoch #121 + #124
