### ISSUE TITLE
Komplexné testovanie

### ISSUE THREAD

**Issue by Mcibula** [TIS2023-FMFI/pracovne-cesty#84]
Otestovať všetky komponenty a funkcionality systému podľa [Testovacích scenárov](https://docs.google.com/document/d/1AyoBpdD-MUP3xzU5pTLfqsbvmHi-Pdisp0YhS7-p1vY/edit?usp=drive_link) / #26 

- [x] Testovanie `BusinessTripController` #102 
- [x] Testovanie exportovania PDF #96 
- [x] Testovanie user managementu #98 + #101 
- [x] Testovanie synchronizácie s Prítomnosťou #115 
- [x] Testovanie `SppController`
- [x] Vysokoúrovňové testovanie podľa Testovacích scenárov
